exclude: ^(.*\/migrations|.*package.json|.*package-lock.json|Pipfile*)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
        exclude: tests/
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: tests/test_changes/
        files: \.(py|sh|rst|yml|yaml)$
      - id: mixed-line-ending
      - id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        exclude: tests/|white_rabbit/migrations
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-blind-except',
          'flake8-bugbear',
          'flake8-comprehensions',
          'flake8-implicit-str-concat',
        ]
        exclude: ^tests/test_cases/no_closing_bracket\.py$

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [ black==23.9.1 ]
        exclude: ^.github/
  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.2.0
    hooks:
      - id: rstcheck
        args: [
          --report-level=warning,
        ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    hooks:
      - id: python-safety-dependencies-check
    rev: v1.3.3
  - hooks:
      - id: beautysh
    repo: https://github.com/bemeurer/beautysh.git
    rev: v6.2.1
  - hooks:
      - id: script-must-have-extension
    repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
  - hooks:
      - id: check-xml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
  - hooks:
      - args:
          - '-d {rules: {line-length: {max: 999}}}'
        id: yamllint
    repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
  - hooks:
      - id: check-yaml
      - id: sort-simple-yaml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
  - hooks:
      - id: check-json
      - args:
          - --autofix
        id: pretty-format-json
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
  - hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs
    repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
  - hooks:
      - id: pyupgrade
    repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
