---

- name: "daily email reminders for {{ group_names[0] }}"
  cron:
    user: "{{ main_user }}"
    name: "{{ project_slug }} daily email reminders"
    hour: "9"
    minute: "0"
    job: "/usr/local/bin/{{ project_slug }}-ctl send_email_reminders"
    state: "{{ 'present' if group_names[0] == 'prod' else 'absent' }}"

- name: "hydrate cache"
  cron:
    user: "{{ main_user }}"
    name: "{{ project_slug }} hydrate cache"
    minute: "*/{{ 5 if group_names[0] == 'prod' else 30 }}"
    job: "/usr/local/bin/{{ project_slug }}-ctl hydrate_cache"

- name: "daily database backup"
  cron:
    user: "{{ main_user }}"
    name: "{{ project_slug }} daily database backup"
    day: "*"
    hour: "3"
    job: "/usr/local/bin/{{ project_slug }}-ctl backup_db backup"
  when: group_names[0] == 'prod'
