# Generated by Django 3.1.7 on 2021-03-11 20:13

from django.db import migrations
from django.db.migrations import RunPython

EMPLOYEES = [
    ("Maxime", "https://calendar.google.com/calendar/ical/0rn9t0elkuafqm6401rossmd8g%40group.calendar.google.com/public/basic.ics"),
    ("Antoine", "https://calendar.google.com/calendar/ical/aecj13q1d2q7nu34lflrb7ssc0%40group.calendar.google.com/public/basic.ics"),
    ("Quentin", "https://calendar.google.com/calendar/ical/62kd60uah4s7cbs6j1qoobc3f0%40group.calendar.google.com/public/basic.ics"),
]


def add_employees(apps, schema_editor):
    Employee = apps.get_model("projects_dashboard", "Employee")
    for employee in EMPLOYEES:
        Employee.objects.create(name=employee[0], calendar_ical_url=employee[1])


class Migration(migrations.Migration):

    dependencies = [
        ('projects_dashboard', '0001_initial'),
    ]

    operations = [
        RunPython(add_employees)
    ]
