# Generated by Django 3.1.7 on 2021-06-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0003_auto_20210328_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'entreprise',
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
