# Generated by Django 3.2.4 on 2021-06-18 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('white_rabbit', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admins',
            field=models.ManyToManyField(related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
