# Generated by Django 3.2.4 on 2021-06-21 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0007_auto_20210621_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='start_time_tracking_from',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Début du suivi de temps'),
        ),
    ]
