# Generated by Django 3.2.4 on 2021-06-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0008_employee_start_time_tracking_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='calendar_ical_url',
            field=models.CharField(help_text='"Adresse publique au format iCal" si le calendrier est public, sinon "Adresse privée au format iCal"', max_length=150, verbose_name='URL calendrier Google'),
        ),
    ]
