# Generated by Django 3.2.4 on 2021-11-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0012_alias_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='name',
            field=models.CharField(max_length=32, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=32, verbose_name='nom'),
        ),
    ]
