# Generated by Django 3.2.4 on 2021-11-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0014_project_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='end_time_tracking_on',
            field=models.DateField(blank=True, help_text="Date de fin de contrat d'un salarié, le cas échéant", null=True, verbose_name='Fin du suivi de temps'),
        ),
    ]
