# Generated by Django 3.2.4 on 2021-11-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0015_employee_end_time_tracking_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='calendar_ical_url',
            field=models.CharField(help_text='"Adresse publique au format iCal" si le calendrier est public, sinon "Adresse secrète au format iCal"', max_length=150, verbose_name='URL calendrier Google'),
        ),
        migrations.AddIndex(
            model_name='alias',
            index=models.Index(fields=['name'], name='white_rabbi_name_ee8f1f_idx'),
        ),
    ]
