# Generated by Django 3.2.4 on 2021-11-17 08:54

from django.db import migrations, models


def set_lowercase_name(apps, _):
    Alias = apps.get_model("white_rabbit", "Alias")
    Project = apps.get_model("white_rabbit", "Project")
    for alias in Alias.objects.all():
        alias.lowercase_name = alias.name.lower()
        alias.save()
    for project in Project.objects.all():
        project.lowercase_name = project.name.lower()
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0016_auto_20211117_0844'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alias',
            name='white_rabbi_name_ee8f1f_idx',
        ),
        migrations.AddField(
            model_name='alias',
            name='lowercase_name',
            field=models.CharField(max_length=32, null=True, verbose_name='nom en minuscule'),
        ),
        migrations.AddField(
            model_name='project',
            name='lowercase_name',
            field=models.CharField(max_length=32, null=True, verbose_name='nom en minuscule'),
        ),
        migrations.AddIndex(
            model_name='alias',
            index=models.Index(fields=['lowercase_name'], name='white_rabbi_lowerca_c45c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['lowercase_name'], name='white_rabbi_lowerca_f5cb65_idx'),
        ),
        migrations.RunPython(set_lowercase_name, lambda _, _2: None)
    ]
