# Generated by Django 3.2.4 on 2021-11-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0017_auto_20211117_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='lowercase_name',
            field=models.CharField(default='lowercasename', max_length=32, unique=True, verbose_name='nom en minuscule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='lowercase_name',
            field=models.CharField(default='lowercasename', max_length=32, unique=True, verbose_name='nom en minuscule'),
            preserve_default=False,
        ),
    ]
