# Generated by Django 3.2.4 on 2021-11-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('white_rabbit', '0018_auto_20211117_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='lowercase_name',
            field=models.CharField(max_length=32, verbose_name='nom en minuscule'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lowercase_name',
            field=models.CharField(max_length=32, verbose_name='nom en minuscule'),
        ),

    ]
