# Generated by Django 3.2.10 on 2022-05-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0020_auto_20220523_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='days_sold',
            field=models.DecimalField(decimal_places=1, default=0, help_text="Il s'agit du nombre de jours vendu au client pour ce projet", max_digits=4, verbose_name='Jours vendus'),
        ),
    ]
