# Generated by Django 3.2.10 on 2022-05-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0020_auto_20220517_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='days_sold',
            field=models.IntegerField(default=0, help_text="Il s'agit du nombre de jours vendu au client pour ce projet", verbose_name='Jours vendus'),
        ),
    ]
