# Generated by Django 3.2.10 on 2022-11-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0021_alter_project_days_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='calendar_ical_url',
            field=models.CharField(help_text='"Adresse publique au format iCal" si le calendrier est public, sinon "Adresse secrète au format iCal"', max_length=256, verbose_name='URL calendrier Google'),
        ),
    ]
