# Generated by Django 3.2.10 on 2022-05-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0021_alter_project_days_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_client_project',
            field=models.BooleanField(default=False, verbose_name='Projet client'),
        ),
    ]
