# Generated by Django 3.2.10 on 2023-06-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0023_auto_20230224_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='works_day_1',
            field=models.BooleanField(default=True, verbose_name='travaille le lundi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='works_day_2',
            field=models.BooleanField(default=True, verbose_name='travaille le mardi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='works_day_3',
            field=models.BooleanField(default=True, verbose_name='travaille le mercredi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='works_day_4',
            field=models.BooleanField(default=True, verbose_name='travaille le jeudi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='works_day_5',
            field=models.BooleanField(default=True, verbose_name='travaille le vendredi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='works_day_6',
            field=models.BooleanField(default=False, verbose_name='travaille le samedi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='works_day_7',
            field=models.BooleanField(default=False, verbose_name='travaille le dimanche'),
        ),
    ]
