# Generated by Django 3.2.10 on 2024-05-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0023_auto_20240430_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('PRO_BONO', 'Pro-bono'), ('CLIENT', 'Client'), ('INTERNAL', 'Interne'), ('ROLE', 'Rôle'), ('OTHER', 'Autre'), ('OFF_WORK', 'Congé'), ('', 'Non défini')], max_length=12),
        ),
    ]
