# Generated by Django 3.2.10 on 2024-02-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0024_auto_20230622_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_pro_bono_project',
            field=models.BooleanField(default=False, verbose_name='Projet pro bono'),
        ),
    ]
