# Generated by Django 3.2.10 on 2024-05-15 10:02

from django.db import migrations, models


def client_and_pro_bono_to_category(apps, schema_editor):
    Project = apps.get_model('white_rabbit', 'Project')
    for project in Project.objects.all():
        if project.is_client_project:
            project.category = "CLIENT"
        elif project.is_pro_bono_project:
            project.category = 'PRO_BONO'
        project.save()


class Migration(migrations.Migration):
    dependencies = [
        ('white_rabbit', '0025_project_is_pro_bono_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Salarié désactivé', verbose_name='désactivé'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True,
                                   choices=[('PRO_BONO', 'Pro-bono'), ('CLIENT', 'Client'), ('INTERNAL', 'Interne'),
                                            ('ROLE', 'Rôle'), ('OTHER', 'Autre'), ('OFF_WORK', 'Congé'),
                                            ('', 'Non défini')], max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('lowercase_name', 'name', 'company', 'category', 'start_date', 'end_date')},
        ),
        migrations.RunPython(
            code=client_and_pro_bono_to_category,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_client_project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_pro_bono_project',
        ),
    ]
