# Generated by Django 3.2.10 on 2024-04-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('white_rabbit', '0026_employee_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('lowercase_name', 'company', 'start_datetime')},
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_datetime',
        ),
    ]
