# Generated by Django 3.2.10 on 2024-04-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0026_employee_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_client_project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_pro_bono_project',
        ),
        migrations.AddField(
            model_name='project',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
