# Generated by Django 5.0.6 on 2024-07-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0027_auto_20240531_0758"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRO_BONO", "Pro-bono"),
                    ("CLIENT", "Client"),
                    ("INTERNAL", "Interne"),
                    ("ROLE", "Rôle"),
                    ("OTHER", "Autre"),
                    ("OFF_WORK", "Congé"),
                    ("OKLM", "Oklm"),
                    ("", "Non défini"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="estimated_days_count",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Nombre de jours prévus sur le projet",
                max_digits=4,
                verbose_name="Jours prévus",
            ),
        ),
    ]
