# Generated by Django 3.2.10 on 2024-04-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_rabbit', '0027_auto_20240422_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('PRO_BONO', 'Pro-bono'), ('CLIENT', 'Client'), ('INTERNAL', 'Interne')], max_length=12),
        ),
    ]
