# Generated by Django 5.0.6 on 2024-10-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0028_alter_project_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="daily_employee_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Coût journalier moyen d'un salarié pour l'entreprise en € (salaire moyen brut chargé / nb jours travaillés)",
                max_digits=6,
                verbose_name="Coût salarié journalier moyen",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="daily_market_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tarif journalier moyen exercé sur le marché en €",
                max_digits=6,
                verbose_name="Prix du marché",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="profitability_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Le seuil journalier de rentabilité, en €, prend en compte que tous les jours ne sont pas travaillés (commercial, formation) et intègre les coûts de structure (support, loyer, logiciels...)",
                max_digits=6,
                verbose_name="Seuil de rentabilité",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_sold",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant total vendu pour le projet en € (hors coûts refacturés)",
                max_digits=10,
                verbose_name="Total vendu",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRO_BONO", "Pro-bono"),
                    ("CLIENT", "Client"),
                    ("INTERNAL", "Interne"),
                    ("ROLE", "Rôle"),
                    ("OTHER", "Autre"),
                    ("OFF_WORK", "Congé"),
                    ("OKLM", "Oklm"),
                    ("SALES", "Commercial"),
                    ("", "Non défini"),
                ],
                max_length=12,
            ),
        ),
    ]
