# Generated by Django 5.0.6 on 2024-11-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0028_alter_project_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRO_BONO", "Pro-bono"),
                    ("CLIENT", "Client"),
                    ("INTERNAL", "Interne"),
                    ("ROLE", "Rôle"),
                    ("OTHER", "Autre"),
                    ("OFF_WORK", "Congé"),
                    ("OKLM", "Oklm"),
                    ("SALES", "Commercial"),
                    ("", "Non défini"),
                ],
                max_length=12,
            ),
        ),
    ]
