# Generated by Django 5.0.6 on 2024-10-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "white_rabbit",
            "0029_company_employee_real_cost_company_market_cost_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="rentability_cost",
            new_name="break_even_point",
        ),
    ]
