# Generated by Django 5.0.6 on 2024-11-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0029_company_daily_employee_cost_and_more"),
        ("white_rabbit", "0029_project_notes_alter_project_category"),
    ]

    operations = []
