# Generated by Django 5.0.6 on 2024-11-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0032_project_created_project_modified_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Catégorie"},
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={
                (
                    "lowercase_name",
                    "name",
                    "company",
                    "category_instance",
                    "start_date",
                    "end_date",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "company")},
        ),
        migrations.RemoveField(
            model_name="project",
            name="category",
        ),
    ]
