# Generated by Django 5.0.6 on 2024-11-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "white_rabbit",
            "0033_alter_category_options_alter_project_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="category_instance",
            new_name="category",
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={
                (
                    "lowercase_name",
                    "name",
                    "company",
                    "category",
                    "start_date",
                    "end_date",
                )
            },
        ),
    ]
