# Generated by Django 5.0.6 on 2024-11-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0034_rename_category_instance_project_category_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=(
                    "lowercase_name",
                    "name",
                    "company",
                    "category",
                    "start_date",
                    "end_date",
                ),
                name="project name",
                nulls_distinct=False,
            ),
        ),
    ]
