# Generated by Django 5.0.6 on 2024-11-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0036_auto_20241127_1130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                default="bg-yellow-100",
                help_text="Couleur de la catégorie, <a href= 'https://tailwindcss.com/docs/background-color'>référence</a>",
                max_length=32,
                verbose_name="couleur",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
        ),
        migrations.AlterField(
            model_name="category",
            name="modified",
            field=models.DateField(auto_now=True, verbose_name="modifié le"),
        ),
        migrations.AlterField(
            model_name="company",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
        ),
        migrations.AlterField(
            model_name="company",
            name="modified",
            field=models.DateField(auto_now=True, verbose_name="modifié le"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="modified",
            field=models.DateField(auto_now=True, verbose_name="modifié le"),
        ),
        migrations.AlterField(
            model_name="project",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
        ),
        migrations.AlterField(
            model_name="project",
            name="modified",
            field=models.DateField(auto_now=True, verbose_name="modifié le"),
        ),
    ]
