# Generated by Django 5.0.6 on 2025-01-14 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0037_alter_category_color_alter_category_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "modified",
                    models.DateField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "number",
                    models.CharField(max_length=32, verbose_name="numéro de facture"),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant de la facture en € (hors coûts refacturés)",
                        max_digits=10,
                        verbose_name="montant (€ HT)",
                    ),
                ),
                (
                    "days_count",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Nombre de jours facturés",
                        max_digits=4,
                        verbose_name="jours",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="commentaire")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="white_rabbit.project",
                        verbose_name="projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "facture",
            },
        ),
    ]
