# Generated by Django 5.0.6 on 2025-01-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0039_auto_20250114_1603"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="comment",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="numéro de facture"
            ),
        ),
    ]
