# Generated by Django 5.0.12 on 2025-02-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0040_alter_invoice_comment_alter_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_working_time",
            field=models.BooleanField(
                default=True,
                help_text="La catégorie est-elle un temps de travail ? Décocher par exemple pour les congés.",
                verbose_name="est du temps de travail",
            ),
        ),
    ]
