# Generated by Django 5.0.12 on 2025-02-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0041_alter_invoice_options_employee_is_paid_hourly_and_more"),
        ("white_rabbit", "0041_category_is_working_time"),
    ]

    operations = []
