# Generated by Django 5.0.12 on 2025-03-16 14:04

from django.db import migrations, models


def only_keep_more_recent_projects_on_duplicates(apps, schema_editor):
    Project = apps.get_model("white_rabbit", "Project")
    deleted = []
    for project in tqdm(Project.objects.order_by("-pk"), total=Project.objects.count()):
        if project.invoices.count() or project.aliases.count():
            continue
        query = {
            "name": project.name,
            "company": project.company,
        }
        if project.start_date:
            query["start_date"] = project.start_date
        else:
            query["start_date__isnull"] = True
        if Project.objects.filter(
            **query
        ).exclude(pk=project.pk).exists():
            deleted.append(f"{project.name} - {project.start_date} ({project.company.name})")
            project.delete()
    if deleted:
        print(f"Deleted {len(deleted)} projects:\n {', '.join(deleted)}")

class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0042_merge_20250218_0824"),
    ]

    operations = [
        migrations.RunPython(only_keep_more_recent_projects_on_duplicates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="alias",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="numéro de facture/devis",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("name", "company", "start_date")},
        ),
    ]
