# Generated by Django 5.0.12 on 2025-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0043_alter_alias_name_alter_invoice_number_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="project name",
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("name", "company", "start_date"),
                name="project name",
                nulls_distinct=False,
            ),
        ),
    ]
