# Generated by Django 5.0.12 on 2025-07-25 08:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0044_remove_project_project_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeForecastAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide pour utiliser la date de début du projet prévisionnel",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide pour utiliser la date de fin du projet prévisionnel",
                        null=True,
                    ),
                ),
                (
                    "estimated_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Nombre total de jours estimés pour cet employé sur ce projet",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation prévisionnelle",
                "verbose_name_plural": "Affectations prévisionnelles",
            },
        ),
        migrations.CreateModel(
            name="ForecastProject",
            fields=[
                (
                    "project_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="white_rabbit.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "projet prévisionnel",
                "verbose_name_plural": "projets prévisionnels",
            },
            bases=("white_rabbit.project",),
        ),
        migrations.RemoveConstraint(
            model_name="project",
            name="project name",
        ),
        migrations.AddField(
            model_name="project",
            name="is_forecast",
            field=models.BooleanField(
                default=False, help_text="Projet prévisionnel", verbose_name="Prévision"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("name", "company", "start_date", "is_forecast"),
                name="project name",
                nulls_distinct=False,
            ),
        ),
        migrations.AddField(
            model_name="employeeforecastassignment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecast_assignments",
                to="white_rabbit.employee",
            ),
        ),
        migrations.AddField(
            model_name="forecastproject",
            name="forecast_employees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Employés affectés à ce projet prévisionnel",
                through="white_rabbit.EmployeeForecastAssignment",
                to="white_rabbit.employee",
                verbose_name="employés prévisionnels",
            ),
        ),
        migrations.AddField(
            model_name="employeeforecastassignment",
            name="forecast_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_assignments",
                to="white_rabbit.forecastproject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeeforecastassignment",
            unique_together={("employee", "forecast_project", "start_date")},
        ),
    ]
