# Generated by Django 5.0.12 on 2025-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0044_remove_project_project_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastProject",
            fields=[],
            options={
                "verbose_name": "projet prévisionnel",
                "verbose_name_plural": "projets prévisionnels",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("white_rabbit.project",),
        ),
        migrations.RemoveConstraint(
            model_name="project",
            name="project name",
        ),
        migrations.AddField(
            model_name="project",
            name="is_forecast",
            field=models.BooleanField(
                default=False, help_text="Projet prévisionnel", verbose_name="Prévision"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("name", "company", "start_date", "is_forecast"),
                name="project name",
                nulls_distinct=False,
            ),
        ),
    ]
