# Generated by Django 5.0.12 on 2025-07-18 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0045_forecastproject_remove_project_project_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeForecastAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "estimated_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Nombre total d'heures estimées pour cet employé sur ce projet",
                        max_digits=6,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_assignments",
                        to="white_rabbit.employee",
                    ),
                ),
                (
                    "forecast_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_assignments",
                        to="white_rabbit.forecastproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation prévisionnelle",
                "verbose_name_plural": "Affectations prévisionnelles",
                "unique_together": {("employee", "forecast_project", "start_date")},
            },
        ),
    ]
