# Generated by Django 5.0.12 on 2025-09-15 08:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0045_employeeforecastassignment_forecastproject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="reminders_frequency",
            field=models.CharField(
                choices=[("daily", "Quotidien"), ("weekly", "Hebdomadaire")],
                default="daily",
                help_text="Fréquence d'envoi des rappels par email pour les jours manquants",
                max_length=10,
                verbose_name="fréquence des rappels",
            ),
        ),
        migrations.AlterField(
            model_name="employeeforecastassignment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecast_assignments",
                to="white_rabbit.employee",
                verbose_name="salarié",
            ),
        ),
        migrations.AlterField(
            model_name="employeeforecastassignment",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Laisser vide pour utiliser la date de fin du projet prévisionnel",
                null=True,
                verbose_name="date de fin",
            ),
        ),
        migrations.AlterField(
            model_name="employeeforecastassignment",
            name="estimated_days",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Nombre total de jours estimés pour cet employé sur ce projet",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="jours estimés",
            ),
        ),
        migrations.AlterField(
            model_name="employeeforecastassignment",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Laisser vide pour utiliser la date de début du projet prévisionnel",
                null=True,
                verbose_name="date de début",
            ),
        ),
    ]
