# Generated by Django 5.0.12 on 2026-03-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0046_add_reminders_frequency_to_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="subproject_names",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Noms des sous-projets détectés dans le calendrier",
                verbose_name="sous-projets",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="reminders_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Quotidien"),
                    ("weekly", "Hebdomadaire"),
                    ("never", "Pas de rappel"),
                ],
                default="daily",
                help_text="Fréquence d'envoi des rappels par email pour les jours manquants",
                max_length=10,
                verbose_name="fréquence des rappels",
            ),
        ),
    ]
