# Generated by Django 5.0.12 on 2026-03-06 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0046_add_reminders_frequency_to_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="paid_leave_accrual_start_month",
            field=models.IntegerField(
                default=5,
                help_text="Mois (1-12) du début de la période d'acquisition des congés payés. Ex: 1 pour janvier, 5 pour mai.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="mois de début d'acquisition des congés payés",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="rtt_acquisition_month",
            field=models.IntegerField(
                default=1,
                help_text="Mois (1-12) du 1er jour auquel les RTT sont attribués chaque année.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="mois d'acquisition des RTT",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="annual_paid_leave_days",
            field=models.DecimalField(
                decimal_places=1,
                default=25,
                help_text="Nombre de jours de congés payés acquis sur l'année d'acquisition (ex: 25)",
                max_digits=4,
                verbose_name="jours de congés payés annuels",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="annual_rtt_days",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Nombre de jours RTT alloués à la date d'acquisition. Mettre 0 si pas de RTT.",
                max_digits=4,
                verbose_name="jours RTT annuels",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="leave_type",
            field=models.CharField(
                blank=True,
                choices=[("", "Aucun"), ("CP", "Congés payés"), ("RTT", "RTT")],
                default="",
                help_text="Indique si ce projet correspond à des congés payés (CP) ou des RTT.",
                max_length=3,
                verbose_name="type de congé",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="reminders_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Quotidien"),
                    ("weekly", "Hebdomadaire"),
                    ("never", "Pas de rappel"),
                ],
                default="daily",
                help_text="Fréquence d'envoi des rappels par email pour les jours manquants",
                max_length=10,
                verbose_name="fréquence des rappels",
            ),
        ),
    ]
