# Generated by Django 5.0.12 on 2025-07-21 13:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("white_rabbit", "0046_employeeforecastassignment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ForecastProject",
        ),
        migrations.AddField(
            model_name="project",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Employés assignés au projet",
                to="white_rabbit.employee",
                verbose_name="employés",
            ),
        ),
        migrations.AlterField(
            model_name="employeeforecastassignment",
            name="estimated_hours",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Nombre total d'heures estimées pour cet employé sur ce projet",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.1)],
            ),
        ),
        migrations.CreateModel(
            name="ForecastProject",
            fields=[
                (
                    "project_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="white_rabbit.project",
                    ),
                ),
                (
                    "forecast_employees",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Employés affectés à ce projet prévisionnel",
                        through="white_rabbit.EmployeeForecastAssignment",
                        to="white_rabbit.employee",
                        verbose_name="employés prévisionnels",
                    ),
                ),
            ],
            options={
                "verbose_name": "projet prévisionnel",
                "verbose_name_plural": "projets prévisionnels",
            },
            bases=("white_rabbit.project",),
        ),
        migrations.AlterField(
            model_name="EmployeeForecastAssignment",
            name="forecast_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_assignments",
                to="white_rabbit.forecastproject",
            ),
        ),
    ]
