# Generated by Django 5.0.12 on 2025-07-24 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "white_rabbit",
            "0048_remove_employeeforecastassignment_estimated_hours_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeforecastassignment",
            name="estimated_days",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Nombre total de jours estimés pour cet employé sur ce projet",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.1)],
            ),
        ),
    ]
